### ISSUE TITLE
How to send invitation email?

### ISSUE THREAD

**Issue by abkiran** [spatie/laravel-google-calendar#100]

**Comment by web-developer-8** [comment]
You have to send a null valued first to the save method and then pass the "sendUpdates" property in an array with the value of "all".  I have included a working example below from my code.   

Something to keep in mind is that for gmail to gmail users the initial calendar event is not sent.  For all email address locations outside of google the invitation will be send on the initial creation.  

Hope this helps!  

$data = $event->save(null ,['sendUpdates' => 'all']);
