### ISSUE TITLE
Organizer and notifications not working

### ISSUE THREAD

**Issue by darshanBabu** [spatie/laravel-google-calendar#102]
I've been trying to add a organizer and send notifications to all while creating the event. But both are not working. I'm able to create the event but these two things are not working. You can check my code.

`Event::create([
               'name' => 'Latest Event dsfdsfsdfsdf',
               'location' => '800 Howard St., San Francisco, CA 94103',
               'description' => 'A chance to hear more about Google\'s developer products.',           
               'startDateTime' => Carbon\Carbon::now(),
               'endDateTime' => Carbon\Carbon::now()->addHour(),
               'sendNotifications' => true,
               'sendUpdates' => 'all',
               'organizer' => array('email' => 'test@gmail.com','displayName' => 'Darshan'),
               'attendees' => array(
                array('email' => 'test@gmail.com','displayName' => 'Darshan', 'organizer' => true),
                array('email' => 'darshan@test.com','displayName' => 'Ryan')
              )
            ]); `

I've also added this issue to the stackoverflow. 
[https://stackoverflow.com/questions/54879217/google-calendar-api-not-showing-the-organizer-name-and-sending-notification-emai](url)

**Comment by jammersonf** [comment]
Hello, did you find any solution regarding reminder?

**Comment by atymic** [comment]
Do you get any exceptions or errors, and if so, can you post them?

**Comment by atymic** [comment]
Ping @darshanBabu

**Comment by andretoniati** [comment]
Hello there! I figure out how to sendUpdates.
checkout this post on stackoverflow.
![image](https://user-images.githubusercontent.com/44623399/156769161-1a79ba5f-fd4f-49fd-9987-21ec4504784d.png)
[Stackoverflow](https://stackoverflow.com/questions/51934437/google-calendar-php-api-not-sending-invite-emails)

the function `save()` inside Event class can receive 2 params: string` $method = null, $optParams = []`
On $optParams need pass `sendUpdates="all"`

on my code:

 `$event->save( null, $optParams = ['sendUpdates' => 'all'] );`
