### ISSUE TITLE
Fix: To add Recurrence Events

### ISSUE THREAD

**Issue by seizej** [spatie/laravel-google-calendar#106]
You can add the recurrence events

` $event = new Event();`
`$event->name = $request->get('name')[$key];`
          `  $event->startDateTime = $startDate;`
           ` $event->endDateTime = $endDate;`
            `event->googleEvent->setRecurrence(['RRULE:FREQ=DAILY']);`
` $event->save();`

Now there is I think a bug in the `vendor/spatie/laravel-google-calendar/src/Event.php` file. On line 190  in `setDateProperty()` function it set the timezone of the events dates. Now It is setting the timezone from Carbon timezone object. But according to the Google documentation, it accepts the timezone as a string only. So change the following lines.

From 
`$eventDateTime->setTimezone($date->getTimezone());`
To
`$eventDateTime->setTimezone('UTC'); //or your timezone as string`

After this, you will successfully add the recurrence events.

**Comment by freekmurze** [comment]
Feel free to send a PR to our readme.
