### ISSUE TITLE
Problem with Eventlist

### ISSUE THREAD

**Issue by homeoftheunits** [spatie/laravel-google-calendar#107]
Hi,

i have every day from 2019-04-08 until 2019-04-12 an event in the Google Calendar. So this is my Request:

`$e = Event::get(Carbon\Carbon::parse('2019-04-08'), Carbon\Carbon::parse('2019-04-12'));`

But, i got only the Events until 2019-04-11. What is wrong?

Cheers
Ralf

**Comment by crslp** [comment]
I encountered the same issue. It may depends on differing timezone-settings.
Check you config/app.php and set the correct timezone.
