### ISSUE TITLE
Problem install Laravel 5.8.*

### ISSUE THREAD

**Issue by sebazamorano** [spatie/laravel-google-calendar#117]
Using version ^2.3 for `spatie/laravel-google-calendar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-google-calendar ^2.3 -> satisfiable by spatie/laravel-google-calendar[2.3.0].
    - Conclusion: remove laravel/framework v5.8.35
    - Conclusion: don't install laravel/framework v5.8.35
    - spatie/laravel-google-calendar 2.3.0 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.0.x-dev, 6.x-dev], illuminate/support[6.0.x-dev, 6.x-dev, v6.0.0].
    - Can only install one of: laravel/framework[6.0.x-dev, v5.8.35].
    - Can only install one of: laravel/framework[6.x-dev, v5.8.35].
    - don't install illuminate/support 6.0.x-dev|don't install laravel/framework v5.8.35
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.8.35
    - Installation request for laravel/framework (locked at v5.8.35, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.35].

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
The latest version of the package is Laravel 6 only.

Use an older version of the package to use it in Laravel 5.
