### ISSUE TITLE
Error install spatie/laravel-google-calendar

### ISSUE THREAD

**Issue by at-thaitran** [spatie/laravel-google-calendar#118]
I have error when install spatie/laravel-google-calendar. Please help me!
![image](https://user-images.githubusercontent.com/37789428/64838192-3ea5ea80-d61c-11e9-8140-60ead6e0ffbd.png)

Version:
 - php: 7.3.6
 - laravel: 5.8.31

**Comment by vdbelt** [comment]
You will need to upgrade Laravel to 6.0 to use the latest version of this package. 

If you want to continue using this package with L5.8, you could use version 2.2.* of `spatie/laravel-google-calendar`

**Comment by at-thaitran** [comment]
thank you
