### ISSUE TITLE
new event dinamically Id

### ISSUE THREAD

**Issue by onmigregor** [spatie/laravel-google-calendar#119]
Hi, A pleasure I need change dinamically  calendar_id on  

$event = new Event;

i know to get  

Event::get($rangoI,$rangoF,[], xxxxxx@gmail.com);  

but I need change calendar_id  when I create a new event

**Comment by HeartlandTechie** [comment]
Check out this one: 

https://github.com/spatie/laravel-google-calendar/issues/120

**Comment by onmigregor** [comment]
only use this part?

  // This creates the generic event for public view that resource is unavailable
           $eventtest = Event::create([ 'name' => 'Rental: ' . $info['Resource'], 'id' => NULL, 'startDateTime' => new Carbon\Carbon($info['Date Requested'] . " " . $info['Begin Time'],  'America/Chicago'), 'endDateTime' => new Carbon\Carbon($info['End Time'], 'America/Chicago')], 'your_calendar_id_here@group.calendar.google.com');

**Comment by HeartlandTechie** [comment]
I'm creating two different calendar entries at once - one for a "public' calendar and one with a private entry for others, but my public side uses the default Google calendar setup in the .env variable, and my second one uses that code above with the other Calendar ID . . . clear as mud?
