### ISSUE TITLE
can't save id to google calendar

### ISSUE THREAD

**Issue by amirshawn** [spatie/laravel-google-calendar#12]
If I create a custom id for an event, when I run save() the update method is called instead of it saving.  This creates an error because it's sending a patch request to the url with the id I am trying to insert.  I think the save and update method should be seperated doing away with the check to see if the id exists.  For my personal use I could eliminate having to create the id for the google calendar event if there is a way to retrieve the id google assigns when inserting the event.  It seems like the id is null in the response so I'm not sure if there's another way to retrieve that id so I can save it in my database.

I seperated the methods so I was able to save the id properly but I thought I'd reach out to see if there's a better way.

**Comment by studiovlijmscherp** [comment]
Not really know how to solve this problem, but got the same issue. Event creation simply does an  'UPDATE' instead of a 'PUT' when you send an id with your request. 

There should be a check if the given event-id exists in the Google Calendar, if so - UPDATE. Else PUT.

I modified /vendor/spatie/laravel-google-calendar/src/Event.php to return false (allways) so you can use an own even-id:

`public function exists(): bool
    {
        //return $this->id != '';
        return false;
    }`

**Comment by ramdrupal7** [comment]
facing same issue

public function exists(): bool { //return $this->id != ''; return false; }

**Comment by ramdrupal7** [comment]
What is the PHP Version You are using ?

**Comment by amirshawn** [comment]
my solution was to delete the exists method and I created an update function and seperated it from the save function.  It works good now.  I can share the code with you if you'd like.

**Comment by ramdrupal7** [comment]
Sure you can Amirshawn

**Comment by ramdrupal7** [comment]
PHP 7.0 it is working fine i am using 5.6 this is making issue. so only i asked author what version he is using.

**Comment by freekmurze** [comment]
This is fixed in `v1.0.3`

**Comment by arborrow** [comment]
I am running v1.0.3 and still seem to be having an issue - I was using php's uniqid function to create an id but getting:

Google_Service_Exception in REST.php line 110: Error calling PUT https://www.googleapis.com/calendar/v3/calendars/montserratretreat.org_6rll8gg5fu0tmps7riubl0g0cc%40group.calendar.google.com/events/587054e28e2c3: (404) Not Found

when I go to save. I will keep investigating but am open to any suggestions?

**Comment by arborrow** [comment]
OK, I looked more closely at the code and noticed the option to specify the method type in my code. I changed my controller code 
from: $calendar_event->save();  
to: $calendar_event->save('insertEvent');  
and it worked just fine.

**Comment by brnmonteiro** [comment]
I agree with @arborrow , its not safe check events existence by `id != ''`
