### ISSUE TITLE
Error when create Event: Calendar usage limits exceeded

### ISSUE THREAD

**Issue by at-thaitran** [spatie/laravel-google-calendar#121]
https://github.com/spatie/laravel-google-calendar/security/advisoriesI have error when add mail attendees: `Calendar usage limits exceeded.`. I waited a few days, change account google and tried again but nothing 
![image](https://user-images.githubusercontent.com/37789428/65850293-7cbf4000-e378-11e9-8e75-b98d9b47c5be.png)

**Comment by freekmurze** [comment]
This error is probably not caused by the package.

If there is anything you think the package does wrong, please provide instructions on how to recreate the problem.

**Comment by rafgod-ML** [comment]
I got the same problem, when I test adding attendees is not working, I try creating a new event with attendees and don`t work, edit an event to add attendees and don´t work.
When I create an event without attendees it works fine! also edit an event without adding an attending and works fine.

Did anyone got a solution for this? I already see this error posted in lot of sites and has no answer  that help to fix this

**Comment by manu-mohanan** [comment]
The problem exists in UiPath too while triying to create / modify an event with attendee list. There is an issue logged in google issue tracker. Hope there will be some updates soon. 

["Calendar usage limits exceeded" when adding event with attendee](https://issuetracker.google.com/issues/36761425)
