### ISSUE TITLE
Update on Google Permissions?

### ISSUE THREAD

**Issue by HeartlandTechie** [spatie/laravel-google-calendar#122]
Has anyone reviewed the instructions on how to install this lately?   I recognize the screenshots but nothing matches up to the latest Google API/Calendar access.  Any updates or guidance?

**Comment by freekmurze** [comment]
I did not have to request persmission on Google myself lately. 

I'd gladly accept a PR that brings the readme up to time with the current screens at Google.

**Comment by HeartlandTechie** [comment]
I'm puzzling through that jungle myself . . . I can't figure out how to allow the write access.

**Comment by HeartlandTechie** [comment]
Patience . . . . I did end up getting it to work, the API reads were working but the write required permission, but I couldn't give it permission without waiting 24 hours ??    Google finally allowed me to select to give my API user write access and today it worked fine.  I'm not sure what I did that made the difference.

**Comment by morpheus7CS** [comment]
This issue should now be closed, due to the updated README.md 17 days ago. 

I had all the screenshots done and PR prepared, before checking again. -.-

Kind regards,
g

**Comment by freekmurze** [comment]
Thanks!
