### ISSUE TITLE
add attendee not working

### ISSUE THREAD

**Issue by avni-logistic** [spatie/laravel-google-calendar#125]
I find same issue 

Create event just fine without attendee.

get error with addAttendee

Google_Service_Exception: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "quotaExceeded",
    "message": "Calendar usage limits exceeded."
   }
  ],
  "code": 403,
  "message": "Calendar usage limits exceeded."
 }
}

_Originally posted by @avni-logistic in https://github.com/spatie/laravel-google-calendar/issues/92#issuecomment-540542127_

**Comment by hatja** [comment]
same here, even for the first request for the day..

**Comment by GertjanRoke** [comment]
Same here looks like google just turned this off.

**Comment by celorodovalho** [comment]
Same here, I got it in my first try with addAttendee.

**Comment by celorodovalho** [comment]
Seems to have a problem in Google API:

https://issuetracker.google.com/issues/141704931

**Comment by GertjanRoke** [comment]
Thank you! I will keep watching that issue.

**Comment by manu-mohanan** [comment]
The problem exists in UiPath too while triying to create / modify an event with attendee list. There is an issue logged in google issue tracker. Hope there will be some updates soon.

["Calendar usage limits exceeded" when adding event with attendee](https://issuetracker.google.com/issues/36761425)

**Comment by celorodovalho** [comment]
I just tried to use the **Google API PHP Client** and everything is working pretty fine:

```php
public function testeEvent()
    {
        try {
            $client = new \Google_Client();
            $client->setApplicationName('Google Calendar API PHP Quickstart');
            $client->setScopes([
                \Google_Service_Calendar::CALENDAR,
                \Google_Service_Calendar::CALENDAR_EVENTS,
            ]);
            $client->setAuthConfig('/path-to/credentials.json');
            $client->setAccessType('offline');
            $client->setPrompt('select_account consent');

            $tokenPath = '/path-to/token.json';
            if (file_exists($tokenPath)) {
                $accessToken = json_decode(file_get_contents($tokenPath), true);
                $client->setAccessToken($accessToken);
            }

            // If there is no previous token or it's expired.
            if ($client->isAccessTokenExpired()) {
                // Refresh the token if possible, else fetch a new one.
                if ($client->getRefreshToken()) {
                    $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
                } else {
                    // Request authorization from the user.
                    $authUrl = $client->createAuthUrl();
                    printf("Open the following link in your browser:\n%s\n", $authUrl);
                    print 'Enter verification code: ';
                    $authCode = trim(fgets(fopen('php://stdin', 'r')));

                    // Exchange authorization code for an access token.
                    $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
                    $client->setAccessToken($accessToken);

                    // Check to see if there was an error.
                    if (array_key_exists('error', $accessToken)) {
                        throw new \Exception(join(', ', $accessToken));
                    }
                }
                // Save the token to a file.
                if (!file_exists(dirname($tokenPath))) {
                    mkdir(dirname($tokenPath), 0700, true);
                }
                file_put_contents($tokenPath, json_encode($client->getAccessToken()));
            }

            $service = new \Google_Service_Calendar($client);

            $calendarId = 'CALENDAR_ID_HERE';
            $optParams = array(
                'maxResults' => 10,
                'orderBy' => 'startTime',
                'singleEvents' => true,
                'timeMin' => date('c'),
            );
            $results = $service->events->listEvents($calendarId, $optParams);
            $events = $results->getItems();
            dump($events);

            $evt = new Google_Service_Calendar_Event;
            $evt->setStart(new Google_Service_Calendar_EventDateTime(['dateTime' => \Carbon\Carbon::now()->addDay()]));
            $evt->setEnd(new Google_Service_Calendar_EventDateTime(['dateTime' => \Carbon\Carbon::now()->addDay()->addHour()]));
            $evt->setSummary('TEST TESTS');

            $evt->setAttendees(
                [
                    new \Google_Service_Calendar_EventAttendee(['email' => 'asdf123@gmail.com']),
                    new \Google_Service_Calendar_EventAttendee(['email' => 'fdsa123@gmail.com']),
                ]
            );

            $service->events->insert($calendarId, $evt);
            dump($evt);

        } catch (\Exception $exception) {
            dump($exception);die;
        }
}
```

I just follow this quickstart and could create events with attendees:
https://developers.google.com/calendar/quickstart/php

**Comment by jawwadturabi** [comment]
I am having the same issue. As I am using my service account with nodejs client library and without attendees list it is working fine but with attendees, it is just throwing the error "Calendar usage limits exceeded". So, the quick start guide doesn't help me.

Also if we use the direct expose APIs using access token it is working fine with attendees as mentioned in the quickstart. But in my case I don't want to use quickstart sign-in method due to some reason instead I am using a service account.

This is the request to kindly consider this issue. Thank you

**Comment by web-developer-8** [comment]
Exact same issue here when creating events with attendees. 

Requesting to kindly consider this issue for adding attendees to a calendar event.

**Comment by web-developer-8** [comment]
Okay so after hours of troubleshooting and readying articles on the net I have come to the conclusion that this is a security issue on the Google side for the service account that we are using.   We will need to **"impersonate"** and actual user in order to send calendar events to other individuals.   This is a security update by Google to prevent spamming of calendar events to users.  

I have not worked out the details yet but I am testing the ability to add code below to the GoogleCalendarFactory.php file for this package.  More updates to come soon if I get it working.   I have included some useful links below that I have been using in my troubleshooting. 

`$client->setSubject("user@domain.com");`

[https://issuetracker.google.com/issues/141704931](https://issuetracker.google.com/issues/141704931)

[https://github.com/googleapis/google-api-php-client](https://github.com/googleapis/google-api-php-client)

**Comment by bkintanar** [comment]
This is still occurring, any news of a fix?

Removing attendees successfully creates the calendar event, but when you try to add an attendee, it gives the quota exceeded error.

I also tried creating the event first, then querying the event and attaching the attendee. Upon saving, same error occurs.

**Comment by bkintanar** [comment]
This is still occurring, any news of a fix?

Removing attendees successfully creates the calendar event, but when you try to add an attendee, it gives the quota exceeded error.

I also tried creating the event first, then querying the event and attaching the attendee. Upon saving, same error occurs.

@spatie-bot @ibovangeffen @freekmurze @rubenvanassche @avni-logistic

**Comment by Koen6095** [comment]
I have also the same error as @bkintanar mentioned. No much of activity on the IssueTracker threads from Google.

https://issuetracker.google.com/issues/36761425
https://issuetracker.google.com/issues/141704931

**Comment by patrickleemsantos** [comment]
Any update on this? I was trying also but keep receiving usage limit error

**Comment by patrickleemsantos** [comment]
Hi,

After days of testing, i just did what celorodovalho did. But I added the setSubject method. 

$client->setSubject(env('GOOGLE_CALENDAR_ID'));

Now I can successfully add events to other calendars.
