### ISSUE TITLE
Event id is null after save

### ISSUE THREAD

**Issue by PatrickSummons** [spatie/laravel-google-calendar#129]
I need to store the event id of the event just created in a database for future use, but when i try to see the event id, after i do `$event->save();` with `dd($event->id);` the id is null.

Here is the code i use:

`$event = new Event; 

$event->name = 'event 1';

$event->description = 'event 1';

$event->startDateTime = Carbon::createFromFormat('Y-m-d H:i:s', $date_start);

$event->endDateTime = Carbon::createFromFormat('Y-m-d H:i:s', $date_start)->addHours(2);

$event->save();`

**Comment by GertjanRoke** [comment]
@PatrickSummons you need to reset your event variable like this:

```php
$event = $event->save();
dd($event->id);
```

Then it will work
