### ISSUE TITLE
Return event->id after creation

### ISSUE THREAD

**Issue by studiovlijmscherp** [spatie/laravel-google-calendar#13]
How can we get the googleEvent->id after creating it?

```
$event = new \Spatie\GoogleCalendar\Event;

$event->name = $request->title;
$event->startDateTime = Carbon::parse($request->startDateTime);
$event->endDateTime = Carbon::parse($request->endDateTime);

$event->save();
```

After saving I would like to return the Google Event ID:
```
"googleEvent": {
    ...
    ...
    "id": "7vas6dhkitr3u0te2peqivord4", <-- this one
   ....
}
```
$event->id obviously doens't work because it returns the id of Google_Service_Calendar_Event

**Comment by studiovlijmscherp** [comment]
just found out ([https://developers.google.com/google-apps/calendar/v3/reference/events/insert](https://developers.google.com/google-apps/calendar/v3/reference/events/insert)) we can insert our own unique event_id:


$event_id = 'event'.date('dmYHisu');

$googleEvent->name = $request->title;
$googleEvent->id = $event_id;
$googleEvent->startDateTime = Carbon::parse($request->startDateTime);
$googleEvent->endDateTime = Carbon::parse($request->endDateTime);

**Comment by mclapa** [comment]
@studiovlijmscherp 

I'm getting an error, it seems it's assuming I"m editing an event (the PUT makes me thing that) rather than POST which would be a new one. I use the same code as you:

Error calling PUT https://www.googleapis.com/calendar/v3/calendars/*CALENDARID*/events/*UNIQUE_ID*: (404) Not Found

**Comment by pardamike** [comment]
In case anyone else ends up here from a Google search, and doesn't want to pass in an ID to Google you can do this 2 ways:
```
// Method 1
$calendarEvent = Event::create([
                                'name' => 'A new event',
                                'startDateTime' => Carbon::now(),
                                'endDateTime' => Carbon::now()->addHour(),
                            ]);
// Your ID will be:
$calendarEvent->id;

// Method 2:
```
$event = new Event;
$event->name = 'A new event';
$event->startDateTime = Carbon\Carbon::now();
$event->endDateTime = Carbon\Carbon::now()->addHour();
$calendarEvent = $event->save();
// Your ID will be
$calendarEvent->id;
```

**Comment by partenit** [comment]
Please include in Readme:)

**Comment by AntoineDessauges** [comment]
Need this in readme. Don't know why but this doesn't work 
`    //create event in google calendar
    $event = new Event;

    $event->name = 'A new event';
    $event->startDateTime = Carbon::now();
    $event->endDateTime = Carbon::now()->addHour();

    $event->save();
    dd($event->id);`

But this work 
`    //create event in google calendar
    $event = new Event;

    $event->name = 'A new event';
    $event->startDateTime = Carbon::now();
    $event->endDateTime = Carbon::now()->addHour();

    $event = $event->save(); //need to save it in variable to get the id !
    dd($event->id);`
You need to save your event in your variable when you save it.

(Thank you for your work and just add this because I didn't see it at the begining)

**Comment by arshidkv12** [comment]
Try as follows 

`$event->googleEvent->setId('abc23232323');`
