### ISSUE TITLE
How to specify calendar ID each time?

### ISSUE THREAD

**Issue by cbcto** [spatie/laravel-google-calendar#130]
I understand that I can specify a default calendar in the google-calendar.php file
But how can I specify a different calendar each time I create an event?
E.g. 
Event::create([
   'calendar_id(?)' => 'me@you.com',
   'name' => 'A new event',
   'startDateTime' => Carbon\Carbon::now(),
   'endDateTime' => Carbon\Carbon::now()->addHour(),
]);

**Comment by thepointerschool** [comment]
Pass the calendar ID through as the second parameter on create:

`Event::create([], 'some-domain-com_toid11113bjhk13jh1jkh3bjb123u@group.calendar.google.com')`
