### ISSUE TITLE
Issue with multi day event

### ISSUE THREAD

**Issue by matejvelikonja** [spatie/laravel-google-calendar#135]
I have tried to use to code in the readme.

```php
$event = new Event;

$event->name = 'A new full day event';
$event->startDate = Carbon\Carbon::now();
$event->endDate = Carbon\Carbon::now()->addDay();

$event->save();
```

The event is saved, however in my opinion it does not work as it should, since in Google Calendar it creates a single day event only.

<img width="515" alt="Screenshot 2020-01-03 at 14 44 03" src="https://user-images.githubusercontent.com/1881087/71726481-89e84100-2e37-11ea-97bb-389d1565e94f.png">

Shouldn't the event be extend into 2 days?

**Comment by afrasiyabhaider** [comment]
You should pass the number of days in `Carbon\Carbon::now()->addDay();` 
Carbon\Carbon::now()->addDay(2);

**Comment by matejvelikonja** [comment]
@afrasiyabhaider yeah, this works. thx.
