### ISSUE TITLE
Create Calendar Event with Extended Properties

### ISSUE THREAD

**Issue by web-developer-8** [spatie/laravel-google-calendar#137]
I have been trying to create a calendar event with extended properties however I can't seem to get the syntax to work correctly with the Event::create method.  (Example below)

Do I have my syntax wrong or does the Event:create method not support using extended properties?  I included a link to Google documentation on using extended properties. 

Thanks for all your help! 

// create a new event
Event::create([
   'name' => 'A new event',
   'startDateTime' => Carbon\Carbon::now(),
   'endDateTime' => Carbon\Carbon::now()->addHour(),
   'extendedProperties.private' => array("key" => "value")
]);

https://developers.google.com/calendar/extended-properties

**Comment by freekmurze** [comment]
This is currently not supported. I’d accept a PR that adds support for this to the package.

**Comment by web-developer-8** [comment]
So as it turns out this package natively supports all request body options noted in the Google Calandar api documentation. (Link below)

I would love to create a pull request to update the readme with a few examples so that others don't have to spend hours to figure out native functionality however I don't have rights to create a branch, update the master or create a pull request for this repo.   When you get a moment, will you grant me rights as I would love to contribute?

**Example Usage**    
```php
//CREATE EVENTS
        $event = Event::create([
            'name' => $title,
            'description' => $description,
            'startDateTime' => $start_date,
            'endDateTime' => $end_date,
            'location' => $address,
            'colorId' => 8, //SET TO GREY FOR SHOWING CALENDAR
            'extendedProperties' => array('shared' => array('test' => 'value', 'new' => 'cool'))
        ], null, ['sendUpdates' => 'all'] );
```

**Example Output**
```php
#processed: []
      +"creator": Google_Service_Calendar_EventCreator {#461 ▶}
      +"organizer": Google_Service_Calendar_EventOrganizer {#454 ▶}
      +"start": Google_Service_Calendar_EventDateTime {#474 ▶}
      +"end": Google_Service_Calendar_EventDateTime {#464 ▶}
      +"extendedProperties": Google_Service_Calendar_EventExtendedProperties {#475 ▼
        +private: null
        +shared: array:2 [▼
          "test" => "value"
          "new" => "cool"
        ]
        #internal_gapi_mappings: []
        #modelData: []
        #processed: []
      }
```

**Google Calendar API (Request Body)**
[https://developers.google.com/calendar/v3/reference/events/insert#request-body](https://developers.google.com/calendar/v3/reference/events/insert#request-body)
