### ISSUE TITLE
colorId is returning null even when colors are changed

### ISSUE THREAD

**Issue by artistro08** [spatie/laravel-google-calendar#142]
As of yet, if you set a color for an event in google calendar, the expected output would be the colorId to be a number between 1 and 11. This does not change.

**Comment by artistro08** [comment]
Coding issue. Closing this

**Comment by Riversedgedesigns** [comment]
> 
> 
> Coding issue on my part. Closing this

How did you get it working? I cant find anything on here or on Google API.
