### ISSUE TITLE
multiple users own calendar

### ISSUE THREAD

**Issue by hakkidilek** [spatie/laravel-google-calendar#151]
Can more than one user use their own calendar? I have a Task manager system, can every user use their own google calendar on the system? Or can you merge the calendar that belongs to each user with their own google calendar in the system

**Comment by twf-nikhila** [comment]
@hakkidilek Did u got it working? Looking for a similar feature

**Comment by Irieurb** [comment]
Same here, does anyone have an idea how to set multiple calendars, especially use a different json credentials for every user? Thanks in advance!
