### ISSUE TITLE
Use Delegate domain-wide authority (for those who use G Suite)

### ISSUE THREAD

**Issue by ovitor** [spatie/laravel-google-calendar#152]
Thank you for this library!

I follow the docs and I was able to list events but I'm unable to create events in a given agenda. I got the following error.

```
Google_Service_Exception: {
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "requiredAccessLevel",
    "message": "You need to have writer access to this calendar."
   }
  ],
  "code": 403,
  "message": "You need to have writer access to this calendar."
 }
```

To test, I use some python code and I was able to create event with the example. The difference is that in the python code, I use the delegate domain wide authority, I didn't find in the source if you use it or if you use it at all..

```python
delegated_credentials = credentials.with_subject('tech.sector@example.org')
service = build('calendar', 'v3', credentials=delegated_credentials)
```

My question is: is it possible to use this library with this option of domain-wide authority? The Google docs doesn't show how to do it with PHP (https://developers.google.com/identity/protocols/oauth2/service-account#python). Using this option we don't need to do the steps from Google Agenda like "Add people".

**Comment by jonathanstoker** [comment]
Do you have any idea on how to implement delegated access with this? 
I can't seem to find a workaround to implement this in PHP.

When i add the service account to the calendar i only get read access to free/busy - so i kinda need to access with delegated

**Comment by jonathanstoker** [comment]
Ahh nvm. Saw your recent updates on the pull #153 and i got it working now! 

Thank you so much!!
