### ISSUE TITLE
Error at create new event

### ISSUE THREAD

**Issue by rcarrasquel** [spatie/laravel-google-calendar#159]
Hi,

I have a problem with the implementation and need help. Make all steps and the response is a error at created a new event.

This is the error return:

Google_Service_Exception
`{ "error": { "errors": [ { "domain": "calendar", "reason": "forbiddenForServiceAccounts", "message": "Service accounts cannot invite attendees without Domain-Wide Delegation of Authority." } ], "code": 403, "message": "Service accounts cannot invite attendees without Domain-Wide Delegation of Authority." } }
`

Regards

**Comment by freekmurze** [comment]
The error indicates there is something wrong with the permissions on your account. The package cannot help to solve this.
