### ISSUE TITLE
Encourage non-Laravel projects to use this package?

### ISSUE THREAD

**Issue by fridde** [spatie/laravel-google-calendar#165]
This package uses Laravel in its name and the installation instructions in the docs use the artisan command.

Yet while reading through the source code it seems that the coupling to Laravel is confined to the creation of the configuration file, if I am not mistaken.

Wouldn't it make sense to have a short clarification early in README.md explaining that this package is easily integratable to non-Laravel projects? Is this a bad idea?

**Comment by freekmurze** [comment]
Feel free to send a PR to make that clear.
