### ISSUE TITLE
Add ability to call Google Calendar API by batch

### ISSUE THREAD

**Issue by tomcodes** [spatie/laravel-google-calendar#167]
Hello,

First of all, thank you very much for this great package that allowed me to get started easily on a project I work on!

I have recently added support for recurring events in that project. This combined with Google Calendar sync leads to _interesting result_.

If I add a daily event with a 1 year limit, this creates 365 events localy. That are being sent one by one to Google Calendar.  
Here is a screenshot to illustrate the timing on 25 new events:

![image](https://user-images.githubusercontent.com/2213846/92238661-fa110000-eeb9-11ea-8f9e-e27808e99766.png)

Apparently [there is a way for Google Calendar to to receive by batch](https://developers.google.com/calendar/batch) but I have just started reading the documentation.

I have thought about using an async library to give our users an immediate feedback while the application is communicating with Google's API but it seems a bit under-productive.

I am willing to investigate some time & effort to implement this feature in this library, but have a few questions for you beforehand:

* Is it something you would accept as a PR if done properly?
* Is the task extremely difficult / easy?
* Would you be willing to mentor me lightly shall I be blocked?

Thank you!

**Comment by akmolina28** [comment]
It sounds like you are trying to create recurring events? This package doesn't support that yet but at least one person has figured out how to get it working: https://github.com/spatie/laravel-google-calendar/issues/164

You could also use a work queue to create the events in the background. That's probably what I would do until I started running into API limits. https://laravel.com/docs/7.x/queues

**Comment by tomcodes** [comment]
Thank you very much for your input! I did not realize that recurring events were supported recently.

I will have a look ASAP. Closing this issue for now as it is not relevant anymore.
