### ISSUE TITLE
Problems adding atendees

### ISSUE THREAD

**Issue by JimmyVazz** [spatie/laravel-google-calendar#170]
When create everything like your tutorial but in the part to add atendees, launch error 403: service accounts cannot invite without domain degelation. I activated that part in services accounts in google cloud but stills showing that error

**Comment by AmirRezaM75** [comment]
seems that it doesn't work with "service account". I used Oauth approach and it works fine.

**Comment by JimmyVazz** [comment]
I tried the same but I couln't initialize and setting the project. Do you have some repo to help me? Please

**Comment by AmirRezaM75** [comment]
You may take a look at my repo [laravel-calendly](https://github.com/AmirRezaM75/laravel-calendly)
Check out ``calendly/src/Console/Commands/GoogleAuthentication.php`` file

**Comment by JimmyVazz** [comment]
Thanks bro!
