### ISSUE TITLE
how to get oauth token?

### ISSUE THREAD

**Issue by yadavsingh** [spatie/laravel-google-calendar#176]
Php quickstart tool is not generating oauth token. how to get it?

**Comment by freekmurze** [comment]
I don't know that tool.

**Comment by yadavsingh** [comment]
I'm talking about this: https://developers.google.com/calendar/quickstart/php
This is generating only credentials.json, not token.json. How to get token.json?

**Comment by akmolina28** [comment]
You need to run the quickstart file

`php quickstart.php`

It will generate the token for you. Or you can scrape the code from the quickstart file and build it into your application so that your client can generate their own tokens.
