### ISSUE TITLE
Impossible to define dynamic user token 

### ISSUE THREAD

**Issue by AntoineGUENEAU** [spatie/laravel-google-calendar#179]
In GoogleCalendarFactory , method createOAuthClient
   ` $client->setAccessToken(file_get_contents($authProfile['token_json']));`
It's meens it's always the same $client who is use.
How to add the event to another user's google account ?

**Comment by khrizzcristian** [comment]
Have you found a solution? I need this also

**Comment by harshuchilzy** [comment]
I am also wondering how to do this
