### ISSUE TITLE
Past events

### ISSUE THREAD

**Issue by joannakosiorowski** [spatie/laravel-google-calendar#187]
Is it possible to get all events from google calendar including past events?

**Comment by freekmurze** [comment]
I guess you can use a start date far in the past.

**Comment by joannakosiorowski** [comment]
But when I use according to your documentation $events =  Event::get(); I
have pull out only future events so where I can set the date to get past
events too ?

śr., 27 sty 2021 o 10:19 Freek Van der Herten <notifications@github.com>
napisał(a):
