### ISSUE TITLE
Error 403 - Service accounts cannot invite attendees without Domain-Wide Delegation of Authority where add Attendee

### ISSUE THREAD

**Issue by kobazzo** [spatie/laravel-google-calendar#189]
I have done all steps of the documentation, but if i create ad event with Attendee there is ad error:

"Error 403 - Service accounts cannot invite attendees without Domain-Wide Delegation of Authority"

**Comment by mrabbani** [comment]
Did you solve this issue @kobazzo ?

**Comment by wasitmirani** [comment]
I have done all steps of the documentation but i'm also phasing issues
"Error 403 - Service accounts cannot invite attendees without Domain-Wide Delegation of Authority"
