### ISSUE TITLE
How to insert from an ics file having Microsoft teams information?

### ISSUE THREAD

**Issue by hdvinhhoang** [spatie/laravel-google-calendar#193]
In my ics file, there are some informations related Microsoft Teams like this:

LOCATION;LANGUAGE=en-US:Microsoft Teams Meeting
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:1456027621
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-SKYPETEAMSMEETINGURL:https://teams.microsoft.com/l/meetup-join/

May I know how can I insert the event included these properties?

**Comment by Kipjr** [comment]
Microsoft uses [RFC2445](https://www.rfc-editor.org/rfc/rfc2445.txt) while Google uses its own format. Two options:

1. You can either 'convert' where possible 

`X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY -->  [transparency] => `

`X-MICROSOFT-CDO-INTENDEDSTATUS:FREE -->  [transparency] => transparant`


[Google Calendar Reference:](https://developers.google.com/calendar/v3/reference/events)
```
transparency
Whether the event blocks time on the calendar. 
Optional. Possible values are:
"opaque" - Default value. The event does block time on the calendar. This is equivalent to setting Show me as to Busy in the Calendar UI.
"transparent" - The event does not block time on the calendar. This is equivalent to setting Show me as to Available in the Calendar UI.
```

2.  Which I use that for my MSShifts2Outlook Power Automate Script, you can include them in the contents/description of the event (possibly lightly obscured using BASE64)
```
TE9DQVRJT047TEFOR1VBR0U9ZW4tVVM6TWljcm9zb2Z0IFRlYW1zIE1lZXRpbmcKWC1NSUNST1NPRlQtQ0RPLUFQUFQtU0VRVUVOQ0U6MApYLU1JQ1JPU09GVC1DRE8tT1dORVJBUFBUSUQ6MTQ1NjAyNzYyMQpYLU1JQ1JPU09GVC1DRE8tQlVTWVNUQVRVUzpURU5UQVRJVkUKWC1NSUNST1NPRlQtQ0RPLUlOVEVOREVEU1RBVFVTOkJVU1kKWC1NSUNST1NPRlQtQ0RPLUFMTERBWUVWRU5UOkZBTFNFClgtTUlDUk9TT0ZULUNETy1JTVBPUlRBTkNFOjEKWC1NSUNST1NPRlQtQ0RPLUlOU1RUWVBFOjAKWC1NSUNST1NPRlQtU0tZUEVURUFNU01FRVRJTkdVUkw6aHR0cHM6Ly90ZWFtcy5taWNyb3NvZnQuY29tL2wvbWVldHVwLWpvaW4v
```
