### ISSUE TITLE
hangoutLink value of response is null, how i can generate it?

### ISSUE THREAD

**Issue by mohamedale** [spatie/laravel-google-calendar#198]
i merged [this commit ](https://github.com/spatie/laravel-google-calendar/pull/174/commits/8dd4844d4bc5c8450a168234a53f81e5b9911290) but nothing change and hangoutLink value still null, how i can generate it?
my question at stackoverflow: https://stackoverflow.com/q/66961076/9632208

**Comment by mohamedale** [comment]
I resolved this issue by replacing `service account` authentication with `oauth`.
* https://developers.google.com/calendar/quickstart/php
* https://github.com/spatie/laravel-google-calendar#authentication-with-oauth2

**Comment by abelnexus** [comment]
How did you get the auth0 token and credentials?

**Comment by mohamedale** [comment]
see this video, it's maybe help you: https://www.youtube.com/watch?v=pOdgE22D-1U&t=406s&ab_channel=MohamedAbogabal
