### ISSUE TITLE
Event::create does not work with other calendars

### ISSUE THREAD

**Issue by naruciakk** [spatie/laravel-google-calendar#2]
Hello.

I tried using Event::create to make an event in a calendar which is not default. Unfortunately, the method does not work with the given id and uses the default one instead. Everything works with the given calendar id, except for this method.

Thanks in advance.

**Comment by freekmurze** [comment]
I'll take a look at this in the coming weeks. If you need this fixed quickly, submit a PR.

**Comment by AntonioGiangrave** [comment]
Hello, 
sorry but I 'm new to laravel .
your code is good for my application but I can not figure out how to integrate the part of event recording .
When you write that "You can fetch all events by simply calling 

> Event :: get ( ) 

  where do I place this code ? in the " Events " folder ?
How do you integrate your code into Route and Controller .
THANKS a lot!

**Comment by freekmurze** [comment]
Fixed by #4
