### ISSUE TITLE
Google_Service_Exception in REST.php line 110: Error calling GET 

### ISSUE THREAD

**Issue by jigsawsoul** [spatie/laravel-google-calendar#20]
Hi,

I am having the following problem with returning events

```Google_Service_Exception in REST.php line 110:
Error calling GET ```

Laravel error.
https://i.imgsafe.org/f5e9c0be5a.png

```
$now          = Carbon::now();
$tomorrow = Carbon::tomorrow();
$meetings  = Event::get($now, $tomorrow);
return $meetings;
```

Any ideas, as to why I am getting this error?

Richard

**Comment by freekmurze** [comment]
You're getting a `404`. Probably this means that the calendar ID you're using is wrong.

**Comment by ztackett11** [comment]
Was getting this same error, this was my exact problem as well.
