### ISSUE TITLE
Can not install due to PHP version 5.6.25.0

### ISSUE THREAD

**Issue by fudgemonday** [spatie/laravel-google-calendar#21]
Hi, 
I got this error after run "composer require spatie/laravel-google-calendar" command.

Could not find package spatie/laravel-google-calendar at any version matching your PHP version 5.6.25.0

Why the package required PHP 7.0? Is there any chance that I can install on PHP 5.6?

Thank you for your great package.

**Comment by freekmurze** [comment]
Hi,

this package use features introduced in PHP 7. If you want it use it on an older version of PHP, fork the package and maintain your own PHP 5 compatible copy.
