### ISSUE TITLE
oauth tokens for each user

### ISSUE THREAD

**Issue by baj84** [spatie/laravel-google-calendar#211]
Hi,

On my website users can go through the google oauth process and provide access to their calendar. I then store the access token and refresh token for that specific user.

How can I use this oauth token with your library?

Thanks!

**Comment by Vicftz** [comment]
Hey, did you find something to use this package like you said ?

Best, V.

**Comment by UltraSoftware0** [comment]
if this problem was solved please let us know

**Comment by baj84** [comment]
I ended up not using this library and just used the google/apiclient-services library directly.
