### ISSUE TITLE
2 problems with Google Calendar

### ISSUE THREAD

**Issue by JuanCruzAGB** [spatie/laravel-google-calendar#229]
I'm having two problems, don't know if it's package fault but when follow the tutorial get this when I want to create the Event.

{ "error": { "errors": [ { "domain": "calendar", "reason": "forbiddenForServiceAccounts", "message": "Service accounts cannot invite attendees without Domain-Wide Delegation of Authority." } ], "code": 403, "message": "Service accounts cannot invite attendees without Domain-Wide Delegation of Authority." } }

I tried to make the calendar with the oauth activated too, but my access_token expire after 3599 seconds and don't know how to refresh it without asking the permissions with the quickstart.php

**Comment by pkarsai** [comment]
I had the same problem and this PR is the answer: https://github.com/spatie/laravel-google-calendar/pull/230

It was created about a month after this issue was raised.
