### ISSUE TITLE
Timezone is set to UTC in Google Agenda eventhough it is properly set locally

### ISSUE THREAD

**Issue by tomcodes** [spatie/laravel-google-calendar#231]
Hello!

I have been using this package for a while and all is great, so for this thank you again!

Recently I realized that events sent to Google Calendar from this package have the wrong timezone set:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/2213846/137186540-11431a8a-56f8-4233-b175-e02e8372068a.png">

It says UTC on Google Calendar but the event is properly set to `Europe/Paris` locally: I added a log here https://github.com/spatie/laravel-google-calendar/blob/master/src/Event.php#L256 and got the following result:

<img width="183" alt="image" src="https://user-images.githubusercontent.com/2213846/137186737-c6397f72-d81f-4211-9d66-c9fc8f931e69.png">

The `$eventDateTime` object (from Google SDK) is properly set to `Europe/Paris`.

Am I doing something wrong or is the issue in Google SDK? Thanks for any input on this one.

**Comment by Jonatasmz** [comment]
having the same problem here. Did you figure  it out?

**Comment by tomcodes** [comment]
No not yet. So it might be necessary to dig a little bit more in the source. I will let you know here as soon as I find something, please do the same ;)

**Comment by rakishii13** [comment]
I am stuck on the same issue, I was trying to pass start.timeZone and end.timeZone as additional parameters based on the https://developers.google.com/calendar/api/v3/reference/events/insert but that did not work and then I also used Carbon to set the right timezone to 'America/New_York' and send it through but that did not work as well.

**Comment by rakishii13** [comment]
Any update from the maintainers?

**Comment by freekmurze** [comment]
I currently have no time to look into this, but I'm happy to review a PR that fixes this. If possible, also add a test.
