### ISSUE TITLE
Error 403 - Service accounts cannot invite attendees without Domain-Wide Delegation of Authority where add Attendee

### ISSUE THREAD

**Issue by 82solutions** [spatie/laravel-google-calendar#243]
add event with Attendee there show mention error:

"Error 403 - Service accounts cannot invite attendees without Domain-Wide Delegation of Authority"</div>

**Comment by andretoniati** [comment]
https://support.google.com/a/answer/162106?hl=en

Read about this, but in summary, the service account be enabled to domain-wide delegation.
Just Google Workspace is possible to have domain-wide delegation.
