### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by AntonioGiangrave** [spatie/laravel-google-calendar#3]
Hello, 
sorry but I 'm new to laravel .
your code is good for my application but I can not figure out how to integrate the part of event recording .
When you write that "You can fetch all events by simply calling

Event :: get ( )
where do I place this code ? in the " Events " folder ?
How do you integrate your code into Route and Controller .
THANKS a lot!

**Comment by freekmurze** [comment]
When you've configured the package according to the installation instructions, you can put `Event::get();` anywhere you want (don't forget to import the facade).

**Comment by AntonioGiangrave** [comment]
Ok, i configured the package as you describe. 
I generate my json file form google following your guide on murze.be but with a simple  "Event::get()->first()->id;" i've got the error : 
"Invalid service account JSON file"
What's wrong?
