### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by cardi777** [spatie/laravel-google-calendar#30]
i got repeat events to work, but for datetime i need to add a timezone.

Do you know how that might be done ?

**Comment by freekmurze** [comment]
Not by heart, I guess it should be documented in the API docs at Google.

**Comment by cardi777** [comment]
do you think you will eventually open the door to allow it using your code?

im trying to follow this page for example:

https://developers.google.com/google-apps/calendar/create-events

no matter what i do, it never accepts my timezone despite what appears to be your efforts in Event.php to allow for it?

**Comment by freekmurze** [comment]
I don't need this myself, so haven't researched it. 

I do accept smallish, fully tested, non breaking PRs.

**Comment by cardi777** [comment]
mmm sorry if this sounds like a stupid question

whats a non-breaking pr?

**Comment by cardi777** [comment]
eventually got it to work through trial and error

**Comment by ztackett11** [comment]
The Time Zone should be appended already to the end of the dateTime string returned from the Google API. All you have to do is format it. I used:

` $beginDay = Carbon::parse($start)->format('n-d-Y');
  $endDay   = Carbon::parse($end)->format('n-d-Y');
`
