### ISSUE TITLE
Added events for others

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-google-calendar#35]
I have succesfully setup the complete package, I can add events to my calendar. The thing im wondering, is it possible to add events for other users? Or would they have to upload their api.json file as well and such?

**Comment by freekmurze** [comment]
Haven't had got a need for this functionality myself so didn't investigate. I'd think that by default you can only use your own calendars (and with a little bit of luck delegated calendars).

**Comment by twf-nikhila** [comment]
@Cannonb4ll Did u got it working? Looking for a similar feature
