### ISSUE TITLE
Problem deleting event from calendar

### ISSUE THREAD

**Issue by jringeisen** [spatie/laravel-google-calendar#36]
I have your package installed in my laravel app where photographers can book sessions and the sessions are automatically stored on their google calendar, they can also create custom events, but for some reason they can't delete the event. I can delete my events, but none of the users can delete theres. Below the is destroy method I am using.

    public function destroy($eventId)
        {
            $calendarId = Auth::user()->google_calendar_id;
            $event = Event::find($eventId, $calendarId);
            $event->delete();

            return redirect()->back();
        }

When I dd($event), i get the event so I am not sure why the event isn't being deleted.

**Comment by sebastiandedeyne** [comment]
Are you still experiencing this issue?

**Comment by jringeisen** [comment]
I am, I ended up removing the package and just using full calendar until I can figure out a solution. Do you guys have one?

**Comment by sebastiandedeyne** [comment]
Haven't seen this issue pop up anywhere else yet. I'd recommend starting out by logging this statement to see what exactly gets deleted.

https://github.com/spatie/laravel-google-calendar/blob/master/src/GoogleCalendar.php#L119

**Comment by jringeisen** [comment]
I'm pretty sure the issue has something to do with permissions with google. I decided not to go this route anyway because of a number of steps a user would have to take to get their calendar up and running. I am hoping to find an easier solution. This package seems to work well if you are using it for yourself, not as a tool for other users to use.

**Comment by sebastiandedeyne** [comment]
Since as you say this is most likely a Google permissions related issue, I'm going to close this for now. Feel free to comment for further discussion, or reopen in the future for a bug or feature request related to this!
