### ISSUE TITLE
Creation new Event , get id event create

### ISSUE THREAD

**Issue by wello84** [spatie/laravel-google-calendar#42]
Hi
When create a new Event with:
$event = new Event;
$event->name = 'A new event';
$event->startDateTime = Carbon\Carbon::now();
$event->endDateTime = Carbon\Carbon::now()->addHour();
$event->addAttendee(['email' => 'youremail@gmail.com']);
$event->addAttendee(['email' => 'anotherEmail@gmail.com']);
$event->save();

is possible to get the $eventId created? so i store it and use to modify, delete event in future...

$event = Event::find($eventId);
$event->name = 'My updated title';
$event->save();

many thanks
Nicola

**Comment by sebastiandedeyne** [comment]
I you should be able to access `$event->id` after you've called `save()`.

```php
$event->save();
$eventId = $event->id;
```
