### ISSUE TITLE
Doesn't play well with spatie/laravel-analytics (google/apiclient requirement)

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-google-calendar#43]
Having the `spatie/laravel-google-calendar` package installed prevents `spatie/laravel-analytics` from being installed as the first requires `google/apiclient` version ^1.1.7 and the latter ^2.0.

Saw there was already a closed issue for this (https://github.com/spatie/laravel-google-calendar/issues/31). Is it a big change or does it come down to updating some packages? Either way, I can take a look at it if you need me. Would like to get some Google analytics in my dashboard alongside my calendar events :)

**Comment by freekmurze** [comment]
Hi @sebastiaanluca,

like mentioned in #31 this package isn't high on  my priority list. If you would invest the time to submit a PR to make it work with Google API v2, I'd highly appreciate it.

I'd even be willing to tag a major new release of this package for it so breaking changes are allowed.

**Comment by sebastiaanluca** [comment]
Ok, good to know. I'll check out the changes from v1 to v2 and see if/when I have some time for this :)
