### ISSUE TITLE
Exception after upgrade to v2

### ISSUE THREAD

**Issue by hulkur** [spatie/laravel-google-calendar#47]
changed config as instructed

(1/1) FatalThrowableErrorType error: Argument 1 passed to Spatie\GoogleCalendar\GoogleCalendarFactory::createForCalendarId() must be of the type string, null given, called in /laravel/vendor/spatie/laravel-google-calendar/src/Event.php on line 172

in GoogleCalendarFactory.php (line 10)
at GoogleCalendarFactory::createForCalendarId(null)in Event.php (line 172)
at Event::getGoogleCalendar(null)in Event.php (line 65)
at Event::get(object(Carbon), object(Carbon), array('fields' => 'items(summary,start,end)'))in IndexController.php (line 98)

**Comment by freekmurze** [comment]
Did you set a valid calendar id here: https://github.com/spatie/laravel-google-calendar/blob/c64a870/config/google-calendar.php#L13?

Is so, try flushing config cache with:

```bash
php artisan config:clear
```

**Comment by hulkur** [comment]
yes, calendar id remained from v1

did both config and cache clean

**Comment by hulkur** [comment]
Note to self: file extensions are important!

**Comment by bakkertjebrood** [comment]
@hulkur Could you describe what your issue was? I'm facing the same problem

**Comment by hulkur** [comment]
@bakkertjebrood renamed config file as instructed, but without extension

**Comment by extramex** [comment]
Im facing the same problem, 

This is my google-calendar.php on config folder

`<?php

return [

    /*
     * Path to the json file containing the credentials.
     */
    'service_account_credentials_json' => storage_path('app/google-calendar/service-account-credentials.json'),

    /*
     *  The id of the Google Calendar that will be used by default.
     */
    'calendar_id' => env('contacto@geriatree.site'),
];`
