### ISSUE TITLE
Won't it work in lower php version?

### ISSUE THREAD

**Issue by avastamin** [spatie/laravel-google-calendar#5]
I can't use it for php version. I guess it requires php7. I am wondering if it's possible to use in lover version.

**Comment by freekmurze** [comment]
Nope.

In our business we don't use PHP5.6 anymore. Therefore it makes zero sense for us to maintain PHP5.6 code. Here's [some more info](https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/) on that decision.

Your options are:
- create and maintain your own PHP 5 version of the package (this'll make other devs stuck on PHP 5 happy)
- just copy the code to your application and make it PHP 5 compatible there.
