### ISSUE TITLE
Can we add event to multi account of google calendar?

### ISSUE THREAD

**Issue by sornbarang** [spatie/laravel-google-calendar#50]

**Comment by freekmurze** [comment]
I don't know what a multi account of google calendar is. Do you have a code example of what you're trying to achieve?

**Comment by sornbarang** [comment]
Example:

**Comment by freekmurze** [comment]
Can't you loop through the calendars and create the event in each one?

**Comment by sornbarang** [comment]
Now Done.
` $accCalIds = ['51fnepvjjfc93knop2orf7p2m4@group.calendar.google.com','52fnepvjjfc93knop2orf7p2m4@group.calendar.google.com'];
foreach ($accCalIds as $accCalId) {
            try{
                Event::create([
                  'name' => 'A new event beno 456',
                  'startDateTime' => Carbon::now(),
                  'endDateTime' => Carbon::now()->addHour()
                ], $accCalId);

            }catch(Google_Service_Exception $e){
                \Log::error($e);
            }
        }`
