### ISSUE TITLE
Google Service Exception

### ISSUE THREAD

**Issue by GeoNicol** [spatie/laravel-google-calendar#56]
I believe I followed each step on the tutorial but I keep on getting this error when trying to run the dashboard:fetch-calendar-events command.

` [Google_Service_Exception]
  {
   "error": {
    "errors": [
     {
      "domain": "global",
      "reason": "notFound",
      "message": "Not Found"
     }
    ],
    "code": 404,
    "message": "Not Found"
   }
  }
`

Any hints as to where I might have made a mistake?

**Comment by freekmurze** [comment]
No idea, really. Try asking on a Google user forum.

**Comment by Honest-Objections** [comment]
This error for me, was the result of having the wrong ```service-account-credentials.json``` for the calendar ID being used.

**Comment by agoiabel** [comment]
Please how do I get the right GOOGLE_CALENDAR_ID

**Comment by Altantur** [comment]
@agoiabel  https://help.risevision.com/hc/en-us/articles/115002181123-How-do-I-make-my-google-calendar-public-and-get-the-calendar-ID-
