### ISSUE TITLE
Indirect modification of overloaded element of Google_Service_Calendar_Event has no effect

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-google-calendar#6]
How to set the timezone for the google calendar event? I tried it the same way like all the others but cause of the `array_set()` it resulted in the following exception:

> **Indirect modification of overloaded element of Google_Service_Calendar_Event has no effect**
> at Arr::set(object(Google_Service_Calendar_Event), 'start', 'Europe/Berlin') in helpers.php line 276
> at array_set(object(Google_Service_Calendar_Event), 'start.timeZone', 'Europe/Berlin') in Event.php line 84
> at Event->__set('start.timeZone', 'Europe/Berlin') in Event.php line 37

**Comment by freekmurze** [comment]
A new release is tagged that contains your fix. Thanks!
