### ISSUE TITLE
calendarId null

### ISSUE THREAD

**Issue by rhaynick** [spatie/laravel-google-calendar#66]
Type error: Argument 1 passed to Spatie\GoogleCalendar\GoogleCalendarFactory::createForCalendarId() must be of the type string, null given.

I got this error. Please help

Edit: I solve it by deleting the env(' ') on calendar_id config.

**Comment by naguilar-qf** [comment]
Hi.

How you fixed ? 
I just remove env on config file.

my config file looks like this
return [

    /*
     * Path to the json file containing the credentials.
     */
    'service_account_credentials_json' => storage_path('/storage/app/laravel-google-calendar/service_account_credentials.json'),

    /*
     *  The id of the Google Calendar that will be used by default.
     */
    'calendar_id' => ('calendar_id'),
];


I do know what is wrong, sometimes it says 'file does not exist '; 
Could you please help.

**Comment by rhaynick** [comment]
Could you please check your json file? Make sure it's name the same as
stated on your config and located at storage folder of your laravel blog
(storage/laravel_google_calendar/file_name.json)

**Comment by rhaynick** [comment]
Oh, and the last thing I remember, change your last row on config file as:
'calendar_id' => env('GOOGLE_CALENDAR_ID'),

Hope it help.

**Comment by naguilar-qf** [comment]
Thanks for the help.

this works for me :

'calendar_id' => 'Google_Calendar_id';

Now I got another error,I checked again all the steps on Google Developers and everything is fine.
This is the error #74

**Comment by w33haa2** [comment]
![image](https://user-images.githubusercontent.com/33534250/45470158-2c6e4380-b75f-11e8-8737-633c5472cf8c.png)

tried all the method above, nothing works
