### ISSUE TITLE
laravel 5.5

### ISSUE THREAD

**Issue by Dreknor** [spatie/laravel-google-calendar#68]
Would you update it for laravel 5.5?

`Using version ^2.1 for spatie/laravel-google-calendar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.3.31
    - Conclusion: don't install laravel/framework v5.3.31
    - spatie/laravel-google-calendar 2.1.0 requires illuminate/support ^5.4.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - spatie/laravel-google-calendar 2.1.1 requires illuminate/support ^5.4.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.3.31
    - Installation request for laravel/framework (locked at v5.3.31, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.31].
    - Installation request for spatie/laravel-google-calendar ^2.1 -> satisfiable by spatie/laravel-google-calendar[2.1.0, 2.1.1].

Installation failed, reverting ./composer.json to its original content.`

**Comment by freekmurze** [comment]
It is compatible with Laravel 5.5, but not with Laravel 5.3 which is the version of the framework you are using.
