### ISSUE TITLE
Ability to toggle between different calendars

### ISSUE THREAD

**Issue by jdcrecur** [spatie/laravel-google-calendar#69]
I cannot already see this, but apologies if it is... It would be very helpful to be able to toggle between multiple google calendars within the application. 

From the docs I can only see the ability for the laravel code base to interact with a single google group cal. I need to be able to toggle between different calendars. As in write and read to one for some actions, but then switch to read and write to another.. ie with a completely different json file.

**Comment by dallin** [comment]
Hi @jdcrecur, were you able to figure out a way of doing this?

**Comment by kerwitz** [comment]
You can simply provide the calendar id when calling the package:

`Event::get(null, null, [], 'MY_CALENDAR_ID');`
