### ISSUE TITLE
cannot support for laravel v 5.1.46

### ISSUE THREAD

**Issue by longpq18** [spatie/laravel-google-calendar#72]

**Comment by longpq18** [comment]
How to install laravel-google-calendar for laravel 5.1.46

**Comment by sebastiandedeyne** [comment]
The current version supports Laravel 5.4 and higher. Version 1 of this package supports 5.2, 5.1 was never supported. You'll need to fork this repo or copy and modify the code to your own needs to use it in a 5.1 app.
