### ISSUE TITLE
How to check if an event exists?

### ISSUE THREAD

**Issue by shabaz-ejaz** [spatie/laravel-google-calendar#73]
At the moment if I try to find an event that doesn't exist it throws a `Google_Service_Exception`.

So if I try: `$event = Event::find($eventId);`

If that event does not exist it throws something like the following:

> Google_Service_Exception in REST.php line 110:
> Error calling GET https://www.googleapis.com/calendar/v3/calendars/calendar_name_nrfo11fd4vi2a83ir85b8b2rp0%40group.calendar.google.com/events/eventid: (404) Not Found

Is there any way we can check if it exists without Google API it throwing an exception?

**Comment by shabaz-ejaz** [comment]
Any updates on this??

**Comment by Demaestro** [comment]
You could trap and handle the exception.

Try:

Catch:

**Comment by shabaz-ejaz** [comment]
Yeah but its considered bad practice to have an empty catch as nothing needs to be done there. Would prefer if the package handles this better with a function to maybe check if the event exists.

**Comment by shabaz-ejaz** [comment]
I guess a try catch is sufficient enough for now.

**Comment by mazyvan** [comment]
don't close this issue.  It's a valid petition

**Comment by shabaz-ejaz** [comment]
@mazyvan I agree. At the moment I'm having to wrap all my `Event::find()` calls in an empty try catch block which seems pretty useless and bad practice. Would be better if we had a simple function that allows us to check if an event exists, something like:

`$event = Event::exists($eventId)` and returns either true or false.

**Comment by freekmurze** [comment]
I agree that this can be a pain. I'd accept a PR that return `null` when getting a non existing event id.

Because this is a breaking change, I'll tag a new major version. If there are other breaking changes that you'd like now's the time to send PRs.

**Comment by freekmurze** [comment]
Target all breaking PRs to the `v3` branch.

**Comment by tomhatzer** [comment]
@shabaz-ejaz could you possibly test my WIP PR and give me some feedback if that works for you or any errors that may appear, please?

**Comment by shabaz-ejaz** [comment]
@tomhatzer Sorry I'm not familiar with how to test a WIP PR, how do I test this exactly? I use composer to pull the package down. I am happy to test this, I am happy to test it I'm just not familiar with the process.

**Comment by tomhatzer** [comment]
@shabaz-ejaz the easiest way to try this would be to overwrite your src/Event.php file with the version from the PR (you can also overwrite your version of tests/Integration/EventTest.php with mine and run the phpunit tests if you want, to see if that works too).

Using composer you could load my fork, but you'd have to specify the repository including the url to my fork in your composer.json. I can show you how to do this if you want and replacing the Event.php file is not possible for you.

**Comment by shabaz-ejaz** [comment]
@tomhatzer Okay, so I've just replaced my `src/Event.php` file with the one from your PR.

I went in and created an event as normal and get the following error:

> Type error: Argument 1 passed to Spatie\GoogleCalendar\Event::createFromGoogleCalendarEvent() must be an instance of Google_Service_Calendar_Event, null given, called in /srv/users/asianwed/apps/aws-booking-system/public/vendor/spatie/laravel-google-calendar/src/Event.php on line 95

![2018-08-23_11h05_43](https://user-images.githubusercontent.com/29374282/44519510-21c31000-a6c5-11e8-91e3-5fd22fb092b4.png)

After changing back the the original, it worked perfectly fine and created the event. So this is not quite working correctly at the moment.

Tested from Laravel 5.5 on a live calendar.

**Comment by freekmurze** [comment]
Could somebody test #88 and let me know if it actually works?

**Comment by shabaz-ejaz** [comment]
@freekmurze I did already. See my comment above yours.

**Comment by tomhatzer** [comment]
@shabaz-ejaz Thanks for testing! I'll see if I can get a google account with a few calendar entries to test this thing. I already supposed that this won't work straight away, that's why I made it WIP 😬 
I'll update this as soon as I've made any progress.

If anyone wants to create a google calendar account for this purpose, please feel free to do so and hit me up with the login details so I can use it for testing :)

**Comment by mazyvan** [comment]
For the next major release I think that adding a [`findOrFail` and `firstOrFail`](https://laravel.com/docs/5.6/eloquent#retrieving-single-models) methods would be great as well. Just as a suggestion. That way it would be more concise with laravel models 👍

**Comment by tomhatzer** [comment]
The findOrFail and firstOrFail methods sound like a pretty good idea. I think I'll change my code to reflect these.

**Comment by freekmurze** [comment]
No problem, ping me when you're done.

Closing this for now.

If somebody needs this quick, feel free to submit another PR.

**Comment by rafalau** [comment]
`try {
            Event::find($eventId);
        } catch (\Google_Service_Exception $e) {
            echo $e->getErrors()[0]['reason']; //notFound
        }`
