### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by naguilar-qf** [spatie/laravel-google-calendar#74]
I got the next error trying to create a new event.
I followed carefully all the steps at google developers. I do not know if I miss a step.
-Created my credentials
-Shared my credentials with the calendar

![captura de pantalla 2018-02-07 a la s 13 56 09](https://user-images.githubusercontent.com/36239183/35938507-e710f40a-0c0e-11e8-93a1-b6e9c03a7439.png)

I hope you can help me,
Thank you.

**Comment by JexPY** [comment]
Same problem here, I guess that's the reason -> google calendar doesn't let service anything just "See only free/busy (hide details)" 
![image](https://user-images.githubusercontent.com/9080830/36425451-46691d78-1660-11e8-9d45-4861b8ca923d.png)

**Comment by bhargavkaklotara** [comment]
![untitled](https://user-images.githubusercontent.com/18646257/37462742-fd3b2bde-2878-11e8-90d6-e7b3e1963855.png)

change the configuration here

**Comment by valentinceaprazaru** [comment]
Hello,

i am not sure that this issue has anything to do with your plugin, but if someone has the answer to why I can not update the calendar setting to be able to "make changes to events".

I tried creating a new calendar .. and i am the owner.
