### ISSUE TITLE
I got this error when i run Event::get(); 

### ISSUE THREAD

**Issue by KhairulAzmi21** [spatie/laravel-google-calendar#77]
Hi spatie, thank you for this package. 
I getting some error when try to run Event::get(); . could you help me ?  
<img width="409" alt="screen shot 2018-02-25 at 1 15 27 pm" src="https://user-images.githubusercontent.com/12378983/36638358-fa9868aa-1a2d-11e8-9a11-450ffc1a8624.png">

**Comment by kanwalT** [comment]
how this fixed ?

**Comment by janazthar** [comment]
same problem. How to fix it?
