### ISSUE TITLE
newbie: uncaught error to undefined funtion

### ISSUE THREAD

**Issue by fabianfelix** [spatie/laravel-google-calendar#84]
Hi all,
Could you please help me with this. 
When I try to save or get events. I see this error.
Fatal error: Uncaught Error: Call to undefined function Spatie\GoogleCalendar\config() in C:\xampp\htdocs\kreativ\a2\vendor\spatie\laravel-google-calendar\src\Event.php:185 Stack trace: #0 C:\xampp\htdocs\kreativ\a2\vendor\spatie\laravel-google-calendar\src\Event.php(65): Spatie\GoogleCalendar\Event::getGoogleCalendar(NULL) #1 C:\xampp\htdocs\kreativ\a2\pages\events.1.php(21): Spatie\GoogleCalendar\Event::get() #2 {main} thrown in C:\xampp\htdocs\kreativ\a2\vendor\spatie\laravel-google-calendar\src\Event.php on line 185

eg: when I run $events = Event::get(); the error above is thrown. 
Many thanks in advance.

**Comment by hulkur** [comment]
`composer dumpautoload` maybe. It can't find helper function.

**Comment by fabianfelix** [comment]
Thanks. I tried composer dumpautoload,  but the error remains.

**Comment by freekmurze** [comment]
This is caused by something specific to your app. `config` is a function provided by Laravel itself.

Try installing the package in a vanilla Laravel app to see if that works.
