### ISSUE TITLE
Not return - Event ID

### ISSUE THREAD

**Issue by daniloras** [spatie/laravel-google-calendar#87]
Hello, 

`
$event = new Event;
        $event->name = $data['name'];
        $event->startDateTime = $data['start_datetime'];
        $event->endDateTime = $data['end_datetime'];
        $event->addAttendee(['email' => $data['email_inspector']]);
        $event->addAttendee(['email' => env('GOOGLE_CALENDAR_ID_CATEGORY')]);
        $event->name = $data['name'];
        $event->description = $data['description'];
        $event->location = $data['location'];
        $event->save();

        $eventId = $event->id;
     
        return $eventId;
`

Dont return **$eventId**, please, help-me!

**Comment by mazyvan** [comment]
Having the same issue here

**Comment by mazyvan** [comment]
@daniloras Here is a workaround #55
