### ISSUE TITLE
Generating client secret json

### ISSUE THREAD

**Issue by Raudaschl** [spatie/laravel-google-calendar#9]
Hey,

Thanks for the amazing package.

Thanks so much for the amazing tutorial.

I'm currently having problems generating the correct json file. I followed the example on the blog here perfectly - https://murze.be/2016/05/how-to-setup-and-use-the-google-calendar-api/ , but currently when I generate the json file it creates a "service_account" type json file.

Somehow before I managed to generate a "client secret" json using the method, but this does not seem to work anymore.

I feel like I'm missing something obvious. Please help.

**Comment by belov91** [comment]
How did you manage to fix this?
