### ISSUE TITLE
addAttendee not working

### ISSUE THREAD

**Issue by ibovangeffen** [spatie/laravel-google-calendar#92]
I'm trying to add attendees to an existing calendar event. However, the calendar overwrites the attendees instead of adding the new attendee to the already existing ones.

I tried several things:

```
$event = $this->event->getOne($id);
$calendar = Event::find($event->gcalendar_id); // This is the current google calendar event
$calendar->addAttendee(['email' => 'test@example.com']);
$calendar->save();
```
I also tried foreaching the attendees to check if it would help if I would add all attendees again. I also tried the example on the github page which doesn't work also. And I also tried to add all current email of the attendees in an array, and put it instead of the 'test@example.com' which also didn't work out.

Thanks in advance for your help

**Comment by Mehar-Talha-Saleem** [comment]
Same Issue
@spatie-bot @ibovangeffen @freekmurze  @rubenvanassche  @avni-logistic
