### ISSUE TITLE
How to send adiotionals parameters on save

### ISSUE THREAD

**Issue by callmezarri** [spatie/laravel-google-calendar#93]
I was wondering how to send additional parameters to the insert method of events such as sendUpdates if possible, could give an example of how to do it. Many thanks for the good work !

**Comment by bluespuke** [comment]
According to save(string $method = null, $optParams = []) you can add optional params to the event.

So i tried the following:
`$gevent->save(null, [
    'sendUpdates' => 'all'
]);`
[https://developers.google.com/calendar/v3/reference/events/update](https://developers.google.com/calendar/v3/reference/events/update
)

But i've gotten no mail... Did you made any progress?

**Comment by web-developer-8** [comment]
I am having the exact same issue, are there any updates on passing the sendUpdates param to the ->save method?

**Comment by web-developer-8** [comment]
Figured out a workaround that works if you want to send invites for all events.   I modified the save function in the Event.php file to include the array for $optParams = ['sendUpdates' => 'all'].   This should not have to be hardcoded can we get an update to the function to accept the array from the ->save(['sendUpdates' => 'all']) method?  


public function save(string $method = null, $optParams = []): self
    {
        $method = $method ?? ($this->exists() ? 'updateEvent' : 'insertEvent');

        $googleCalendar = $this->getGoogleCalendar($this->calendarId);

        $this->googleEvent->setAttendees($this->attendees);

        $optParams = ['sendUpdates' => 'all'];

        $googleEvent = $googleCalendar->$method($this, $optParams);

        return static::createFromGoogleCalendarEvent($googleEvent, $googleCalendar->getCalendarId());
    }

**Comment by web-developer-8** [comment]
Update

Using the line of code below when creating a new event works for me to send out alert emails for all.   The code changes above should not be necessary.

$data = $event->save(null ,['sendUpdates' => 'all']);

**Comment by freekmurze** [comment]
Feel free to send a PR for this 👍
