### ISSUE TITLE
Error While Creating the event

### ISSUE THREAD

**Issue by KindleKayPeebit** [spatie/laravel-google-calendar#95]
I am using this function to create the event on Google Calendar
/********* CODE *********************

$event = new Event;
        $event->name = 'A new full day event';
        $event->startDate = Carbon::now();
        $event->endDate = Carbon::now()->addDay(); 
        $event->save();

From your repository

While creating the event I am getting this error

********************* ERROR *****************************

 Google_Service_Exception (403)
{ "error": { "errors": [ { "domain": "calendar", "reason": "requiredAccessLevel", "message": "You need to have writer access to this calendar." } ], "code": 403, "message": "You need to have writer access to this calendar." } } 

I have also followed the instruction mentioned in the following link : 
1) https://stackoverflow.com/questions/14003203/403-forbidden-message-when-calling-the-v3-google-calendar-api-using-a-service-ac
2) https://stackoverflow.com/questions/11863022/edit-google-calendar-events-from-google-service-account-403/11897793#11897793

But still no luck to overcome from this error.

Please update me about this , why I am getting this error. 
Thank you

**Comment by markronquillo** [comment]
<img width="316" alt="screen shot 2018-11-19 at 2 32 16 pm" src="https://user-images.githubusercontent.com/1182515/48690045-f4c0c380-ec07-11e8-8f16-b45100b2d5c5.png">

I tried it, when you share the calendar to the service account email, you should set it with the `Manage changes and sharing`

**Comment by Narayanareddy96** [comment]
I am getting the same error any help here.

Google_Service_Exception (403)
{ "error": { "errors": [ { "domain": "calendar", "reason": "requiredAccessLevel", "message": "You need to have writer access to this calendar." } ], "code": 403, "message": "You need to have writer access to this calendar." } }

do we need auth token for laravel when I am using this package ?

**Comment by web-developer-8** [comment]
If you follow the installation and setup instructions on the code page you should be good.  Make sure to follow every detail for the setup and create a service account to use with laravel that has access to create events in your calendar.   I am currently using this package on a site that went live this week to schedule property showings and create a calendar event for the property showing.

**Comment by pavan-cs** [comment]
@markronquillo can you please explain little more , i am unable to connect how? where ? 
@KindleKayPeebit , same issue how do you fix it?

**Comment by markronquillo** [comment]
Basically you need to allow it to `Make changes to events`.

**Comment by kellerisddev** [comment]
I have created a service account and set the sharing permissions on the calendar to "Make Changes to Events" and I am still getting the Google_Service_Exception Error (403).

I can get events from the calendar but cannot create.

Any other insights?

**Comment by saranshbansal** [comment]
> <img alt="screen shot 2018-11-19 at 2 32 16 pm" width="316" src="https://user-images.githubusercontent.com/1182515/48690045-f4c0c380-ec07-11e8-8f16-b45100b2d5c5.png">
> 
> I tried it, when you share the calendar to the service account email, you should set it with the `Manage changes and manage sharing`
> 
> In case you can't select the `Manage changes and manage sharing`, you can enable it in the admin dashboard, in calendar settings.

I can't find this dropdown anywhere. Can you please guide me.

**Comment by pinoywebs123** [comment]
This error still exist.  I have setup the package with all user permission.
