### ISSUE TITLE
Can i manage multiple calendars?

### ISSUE THREAD

**Issue by bionner** [spatie/laravel-google-calendar#99]
Hi, i just have a simple doubt, i need to manage multiple calendars, can i change the calendar_id on the fly to switch the calendars?

**Comment by freekmurze** [comment]
Currently easy switch is not avaible. But you can use the factory to create your own calendar instances: https://github.com/spatie/laravel-google-calendar/blob/master/src/GoogleCalendarServiceProvider.php#L26

**Comment by AleSpreafico** [comment]
May I ask a quick example of how to create new calendar istances using the factory please?

**Comment by caseylouisee** [comment]
Would you be able to provide an example on how to have multiple calendar instances please? Have tried numerous ways over the past few days but hit a blank.

**Comment by rafalau** [comment]
> May I ask a quick example of how to create new calendar istances using the factory please?

Simple exemple to configure directly in your Controller. 
Just create a controller for each account and you can list the different account data!

![image](https://user-images.githubusercontent.com/15903589/70477493-bcf91800-1ab7-11ea-92d5-567525ec6f0f.png)

**Comment by Badlapje** [comment]
Worked like a charm this.  For anyone using Laravel 8: the import for the config is: `use Illuminate\Support\Facades\Config;
`
